### PR TITLE
Add support for Windows Terminal

### LINKED ISSUE #7: Incorrect results for Windows Terminal
Starting with v1.4, Windows Terminal supports embedded hyperlinks.
However, `supports-hyperlinks` returns `false` for this terminal.

As a workaround, I set the environment variable `FORCE_HYPERLINK`, and everything started working fine.

It happens because there is a piece of code that disables hyperlink support everywhere on Windows (which is not correct):

```js
if (process.platform === 'win32') {
    return false;
}
```

It is possible to understand that we're running in Windows Terminal by checking `env.WT_SESSION` existence; however, it is not so easy to get the actual version of the terminal. See https://github.com/microsoft/terminal/issues/1040 for more details.

### PR DESCRIPTION
**Pull request by dropsonic**
Closes #7

### CODE REVIEW

**Comment by dropsonic** [comment]
@jamestalmage could you please review&merge?

**Comment by jamestalmage** [comment]
@dropsonic I see [the discussion here](https://github.com/microsoft/terminal/issues/1040#issuecomment-756953154).

I understand that a properly implemented terminal will just ignore the special characters, and show the link text. But that can tend to clobber output formatting and alignments. The goal of this module isn't simply to avoid printing control characters (as mentioned, a properly implemented terminal won't display those characters anyways), but to allow authors to conditionally format their output based on how it will be displayed. 

I think we maybe should do a version check. Is that possible? (If I'm understanding the conversations correctly, it seems no). I'm tempted to say get microsoft/terminal/issues/1040 sorted before we merge this. Otherwise we're going to end up clobbering a whole bunch of output.

**Comment by dropsonic** [comment]
@jamestalmage that's correct, there is no way to determine the actual version of Windows Terminal.
I understand your concerns, but in the meantime, the current version of the package also returns an invalid value for Windows Terminal, resulting in an improperly formatted output in the consumer apps.

So, basically, it is a choice between
(a) returning an invalid value for the up-to-date versions of Windows Terminal (as it is now)
or 
(b) returning an invalid value for the outdated versions of Windows Terminal (as it is in this PR).

My assumption is that the vast majority of users install updates from Microsoft Store on time (even automatically) so, in my opinion, (b) is the preferred option.

**Comment by jamestalmage** [comment]
I'm not a Windows user, so I've got limited insights into how frequently Windows Terminal is updated.

I get your argument, and if Windows Terminal sees 99% auto-updates, then maybe it's a valid one. It would be good to understand that as well.

In the most common use case for this package, there's a big difference between returning a false negative, and a false positive. I think [this use](https://github.com/sindresorhus/eslint-formatter-pretty/blob/main/index.js#L139) from [eslint-formatter-pretty](https://github.com/sindresorhus/eslint-formatter-pretty) is fairly representative. If we were to give a false negative, you are inconvenienced and have to google the corresponding eslint rule to find the documentation. If we give a false positive, the output is clobbered and almost unusable.

So, I'm always going to be pretty conservative and favor false negatives over false positives. The bar has to be higher than just "It should be OK for most users", we need to ensure it is right for very nearly everybody. Before this package, tool authors were *avoiding* terminal hyperlinks entirely to maintain the widest possible compatibility. This package encourages more hyperlink use by guaranteeing dependents their output will be usable in the widest array of circumstances.

If somebody from Microsoft is willing to provide some insight into the install base of non-supporting vs supporting terminals, I am willing to reconsider. But it seems like it would be a lot more straightforward for them to just implement any of the recommended solutions in microsoft/terminal/issues/1040. This won't be the last time someone wants to interrogate the terminal version.

**Comment by dropsonic** [comment]
@jamestalmage makes total sense, thanks for the detailed explanation. Ok, let's wait.

**Comment by LitoMore** [comment]
> I get your argument, and if Windows Terminal sees 99% auto-updates, then maybe it's a valid one. It would be good to understand that as well.

FYI:

They are officially recommend installing the Windows Terminal from Microsoft Store: https://github.com/microsoft/terminal#microsoft-store-recommended.

They also provided some ways to install Windows Terminal with package managers and easy to update/upgrade: https://github.com/microsoft/terminal#other-install-methods.

**Comment by nickwesselman** [comment]
Can this be merged now without the need for a version check? Windows terminal [has supported links for almost 4 years now](https://github.com/microsoft/terminal/releases/tag/v1.4.2652.0). [Similar libraries in other languages](https://github.com/zkat/supports-hyperlinks/blob/main/src/lib.rs) include it.

**Pull request merged**
