### PR TITLE
Rewrite with TypeScript & move to ESM

### LINKED ISSUE #15: Supporting typing
Hello! The team over at @stylelint is now using `support-hyperlinks` to show links in terminal output (see https://github.com/stylelint/stylelint/pull/5835). Currently, we've [manually defined types](https://github.com/stylelint/stylelint/pull/5835/files/fc6b53731abbd0f9969b34d8b6071e507e7f3f52#diff-1dfae1a47b7f5557a290b21c0459786cf8f44c25eba59339d3bcd916e1ee8213) for the package, though I think first-class/integrated support would be great!

Do you have a preferred way of doing this with `support-hyperlinks` (ex bundling it with the package, creating something under `@types/`, etc.)? Happy to contribute however I can!

### PR DESCRIPTION
**Pull request by LitoMore**
### Changes

- Rewrite with TypeScript, resolves #15 
- Move to ESM
- Use GitHub Actions
- Drop `.travis.yml`
- Use `c8` instead of `nyc`
- Bump all dependencies to latest
- Remove `supportsHyperlink.stdout` and `supportsHyperlink.stderr`
  - Note: Users can easy implement this API, we could remove it
- Add missing tests
  - Note: There is one uncovered branch, that requires mock `process.env`, but the code to execute is in `supports-color`

### CODE REVIEW

**Comment by sindresorhus** [comment]
I don't really see the point of rewriting such a simple package in TS.

**Comment by LitoMore** [comment]
I noticed the TypeScript definition issue https://github.com/chalk/supports-color/pull/138 while writing this pull request.

I actually solved some potential problems while I was writing this pull request.

For example the `parseVersion` function:

```js
function parseVersion(versionString) {
	if (/^\d{3,4}$/.test(versionString)) {
		// Env var doesn't always use dots. example: 4601 => 46.1.0
		const m = /(\d{1,2})(\d{2})/.exec(versionString);
		return {
			major: 0,
			minor: parseInt(m[1], 10),
			patch: parseInt(m[2], 10)
		};
	}

	const versions = (versionString || '').split('.').map(n => parseInt(n, 10));
	return {
		major: versions[0],
		minor: versions[1],
		patch: versions[2]
	};
}
```

 We are accessing its regex result with `m[1]`, the `m` is possibly `null`.

Although we have `/^\d{3,4}$/.test(versionString)` condition to make sure the `/(\d{1,2})(\d{2})/.exec(versionString)` always have result. But someone else might inadvertently make things go wrong here.

TypeScript can help us to avoid lots of theses kinds of errors.

But if you insist you don't need TypeScript, I can switch back to JavaScript. That's up to you.

**Comment by sindresorhus** [comment]
Let's see what James thinks. It's his repo after all.

**Comment by voxpelli** [comment]
I made a simpler alternative in #21 as I agree with @sindresorhus that TS is overkill for a module like this and simply adding some JSDoc comments can achieve full strict typing with existing code.

**Comment by LitoMore** [comment]
@voxpelli Wow. Thanks.

**Comment by LitoMore** [comment]
Closing in favor of #21.

**Pull request closed without merging**
